# Generated by Django 3.0.4 on 2020-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bookitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Not borrowed'), (1, 'Borrowed')], default=0),
        ),
    ]
