# Generated by Django 3.0.4 on 2020-03-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200324_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(default='00000000', max_length=20),
        ),
    ]
