# Generated by Django 3.0.4 on 2020-03-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200325_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=40, null=True, verbose_name='姓名'),
        ),
    ]
